var TREE_ITEMS = [
	['Home','index.html',{'sb':' '},
		['1. GameSphere.cs', 'GameSphere.cs.html',{'tt':'1. GameSphere.cs','sb':'GameSphere.cs.html'},
			['Variables', 'Variables.html',{'tt':'Variables','sb':'Variables.html'},
				['Materials', 'Materials.html',{'tt':'Materials','sb':'Materials.html'},],
				['SphereRenderer', 'SphereRenderer.html',{'tt':'SphereRenderer','sb':'SphereRenderer.html'},],
				['ActiveContent', 'ActiveContent.html',{'tt':'ActiveContent','sb':'ActiveContent.html'},],
				['InactiveContent', 'InactiveContent.html',{'tt':'InactiveContent','sb':'InactiveContent.html'},],
				['VideoPlayer', 'VideoPlayer.html',{'tt':'VideoPlayer','sb':'VideoPlayer.html'},],
				['MyDissolver', 'MyDissolver.html',{'tt':'MyDissolver','sb':'MyDissolver.html'},],
				['ActiveMaterialIndex', 'ActiveMaterialIndex.html',{'tt':'ActiveMaterialIndex','sb':'ActiveMaterialIndex.html'},],
				['SphereInteractionType', 'SphereInteractionType.html',{'tt':'SphereInteractionType','sb':'SphereInteractionType.html'},],
],
],
		['2. SphereMaterialData.cs', 'SphereMaterialData.cs.html',{'tt':'2. SphereMaterialData.cs','sb':'SphereMaterialData.cs.html'},
			['Material', 'Material.html',{'tt':'Material','sb':'Material.html'},],
			['ContentMediaType', 'ContentMediaType.html',{'tt':'ContentMediaType','sb':'ContentMediaType.html'},],
			['ContentType', 'ContentType.html',{'tt':'ContentType','sb':'ContentType.html'},],
			['SphereInteractionType', 'SphereInteractionType(2).html',{'tt':'SphereInteractionType','sb':'SphereInteractionType(2).html'},],
],
		['3. SphereContentData.cs', 'SphereContentData.cs.html',{'tt':'3. SphereContentData.cs','sb':'SphereContentData.cs.html'},
			['Variables', 'Variables(2).html',{'tt':'Variables','sb':'Variables(2).html'},
				['ContentMediaType', 'ContentMediaType(2).html',{'tt':'ContentMediaType','sb':'ContentMediaType(2).html'},
					['Showif ', 'Showif.html',{'tt':'Showif ','sb':'Showif.html'},
						['ContentMediaTypes', 'ContentMediaTypes.html',{'tt':'ContentMediaTypes','sb':'ContentMediaTypes.html'},
							['Image', 'Image.html',{'tt':'Image','sb':'Image.html'},
								['Texture', 'Texture.html',{'tt':'Texture','sb':'Texture.html'},],
],
							['Video', 'Video.html',{'tt':'Video','sb':'Video.html'},
								['VideoClip', 'VideoClip.html',{'tt':'VideoClip','sb':'VideoClip.html'},],
],
],
],
],
				['ContentType', 'ContentType(2).html',{'tt':'ContentType','sb':'ContentType(2).html'},
					['Showif ', 'Showif(2).html',{'tt':'Showif ','sb':'Showif(2).html'},
						['ContentTypes', 'ContentTypes.html',{'tt':'ContentTypes','sb':'ContentTypes.html'},
							['Inverted', 'Inverted.html',{'tt':'Inverted','sb':'Inverted.html'},
								['InvertedContent list', 'InvertedContentlist.html',{'tt':'InvertedContent list','sb':'InvertedContentlist.html'},],
],
],
],
],
				['VideoClip', 'VideoClip(2).html',{'tt':'VideoClip','sb':'VideoClip(2).html'},],
				['Texture', 'Texture(2).html',{'tt':'Texture','sb':'Texture(2).html'},],
				['Description', 'Description.html',{'tt':'Description','sb':'Description.html'},],
				['InvertedContent list', 'InvertedContentlist(2).html',{'tt':'InvertedContent list','sb':'InvertedContentlist(2).html'},],
],
],
		['4. TransitionManager.cs', 'TransitionManager.cs.html',{'tt':'4. TransitionManager.cs','sb':'TransitionManager.cs.html'},
			['Variables', 'Variables(3).html',{'tt':'Variables','sb':'Variables(3).html'},
				['&lt;inSceneSpheres&gt;()', '.inSceneSpheres.().html',{'tt':'&lt;inSceneSpheres&gt;()','sb':'.inSceneSpheres.().html'},],
				['&lt;sphereMaterial&gt;()', '.sphereMaterial.().html',{'tt':'&lt;sphereMaterial&gt;()','sb':'.sphereMaterial.().html'},],
				['VideoBaseTexture', 'VideoBaseTexture.html',{'tt':'VideoBaseTexture','sb':'VideoBaseTexture.html'},],
				['CurrentSphere', 'CurrentSphere.html',{'tt':'CurrentSphere','sb':'CurrentSphere.html'},],
				['LastTransitionType', 'LastTransitionType.html',{'tt':'LastTransitionType','sb':'LastTransitionType.html'},],
				['CurrentTransitionType', 'CurrentTransitionType.html',{'tt':'CurrentTransitionType','sb':'CurrentTransitionType.html'},],
],
],
		['5. Enums', 'Enums.html',{'tt':'5. Enums','sb':'Enums.html'},
			['ContentMediaTypes | Enum', 'ContentMediaTypes.Enum.html',{'tt':'ContentMediaTypes | Enum','sb':'ContentMediaTypes.Enum.html'},
				['Image', 'Image(2).html',{'tt':'Image','sb':'Image(2).html'},],
				['Video', 'Video(2).html',{'tt':'Video','sb':'Video(2).html'},],
],
			['ContentTypes  | Enum', 'LinkedDocuments/ContentTypes%20%20.mmap',{'tt':'ContentTypes  | Enum','sb':'LinkedDocuments/ContentTypes%20%20.mmap'},],
			['SphereInteractionTypes | Enum', 'SphereInteractionTypes.Enum.html',{'tt':'SphereInteractionTypes | Enum','sb':'SphereInteractionTypes.Enum.html'},
				['NonInteractive', 'NonInteractive.html',{'tt':'NonInteractive','sb':'NonInteractive.html'},],
				['Interactable', 'Interactable.html',{'tt':'Interactable','sb':'Interactable.html'},],
],
			['TransitionTypes | Enum', 'LinkedDocuments/TransitionTypes%20.mmap',{'tt':'TransitionTypes | Enum','sb':'LinkedDocuments/TransitionTypes%20.mmap'},],
],
		['6. Functions Logic', 'FunctionsLogic.html',{'tt':'6. Functions Logic','sb':'FunctionsLogic.html'},
			['Transition()', 'Transition().html',{'tt':'Transition()','sb':'Transition().html'},
				['Arguments', 'Arguments.html',{'tt':'Arguments','sb':'Arguments.html'},
					['Var SphereContentData', 'VarSphereContentData.html',{'tt':'Var SphereContentData','sb':'VarSphereContentData.html'},],
					['Var TransitionTypes', 'VarTransitionTypes.html',{'tt':'Var TransitionTypes','sb':'VarTransitionTypes.html'},],
],
				['ReplaceContent()', 'ReplaceContent().html',{'tt':'ReplaceContent()','sb':'ReplaceContent().html'},
					['SphereInteractionTypes', 'SphereInteractionTypes.html',{'tt':'SphereInteractionTypes','sb':'SphereInteractionTypes.html'},
						['NonInteractive', 'NonInteractive(2).html',{'tt':'NonInteractive','sb':'NonInteractive(2).html'},],
						['Interactable', 'Interactable(2).html',{'tt':'Interactable','sb':'Interactable(2).html'},
							['ReplaceInteractionContent()', 'ReplaceInteractionContent().html',{'tt':'ReplaceInteractionContent()','sb':'ReplaceInteractionContent().html'},
								['Replace material 0 on the Inte... ', 'Replacematerial0ontheInteractionSphereto.html',{'tt':'Replace material 0 on the InteractionSphere to Content','sb':'Replacematerial0ontheInteractionSphereto.html'},],
								['Replace material 1 on the Inte... ', 'Replacematerial1ontheInteractionSphereto.html',{'tt':'Replace material 1 on the InteractionSphere to index 0 of it\'s invertedContent list','sb':'Replacematerial1ontheInteractionSphereto.html'},],
],
],
],
],
				['ContentTypes  | Enum', 'ContentTypes.Enum(2).html',{'tt':'ContentTypes  | Enum','sb':'ContentTypes.Enum(2).html'},
					['Realistic', 'Realistic.html',{'tt':'Realistic','sb':'Realistic.html'},
						['TransitionTypes | Enum', 'TransitionTypes.Enum(2).html',{'tt':'TransitionTypes | Enum','sb':'TransitionTypes.Enum(2).html'},
							['RealisticlToRealistic', 'RealisticlToRealistic.html',{'tt':'RealisticlToRealistic','sb':'RealisticlToRealistic.html'},
								['ReplaceInactiveContent()', 'ReplaceInactiveContent().html',{'tt':'ReplaceInactiveContent()','sb':'ReplaceInactiveContent().html'},
									['Replace material 0 on the inac... ', 'Replacematerial0ontheinactiveNonInteract.html',{'tt':'Replace material 0 on the inactive NonInteractableSphere to Content ','sb':'Replacematerial0ontheinactiveNonInteract.html'},
										['SingleSphereTransition()', 'SingleSphereTransition().html',{'tt':'SingleSphereTransition()','sb':'SingleSphereTransition().html'},],
],
									['Replace material 1 on the Inte... ', 'Replacematerial1ontheInteractionSphereto(2).html',{'tt':'Replace material 1 on the InteractionSphere to index 0 of it\'s invertedContent list','sb':'Replacematerial1ontheInteractionSphereto(2).html'},
										['SphereToSphereTransition()', 'SphereToSphereTransition().html',{'tt':'SphereToSphereTransition()','sb':'SphereToSphereTransition().html'},],
],
],
],
							['RealisticToInverted', 'RealisticToInverted.html',{'tt':'RealisticToInverted','sb':'RealisticToInverted.html'},
								['ReplaceInteractionContent()', 'ReplaceInteractionContent()(2).html',{'tt':'ReplaceInteractionContent()','sb':'ReplaceInteractionContent()(2).html'},
									['Replace material 0 on the Inte... ', 'Replacematerial0ontheInteractionSphereto(2).html',{'tt':'Replace material 0 on the InteractionSphere to Content','sb':'Replacematerial0ontheInteractionSphereto(2).html'},],
									['Replace material 1 on the Inte... ', 'Replacematerial1ontheInteractionSphereto(3).html',{'tt':'Replace material 1 on the InteractionSphere to index 0 of it\'s invertedContent list','sb':'Replacematerial1ontheInteractionSphereto(3).html'},],
],
],
							['InvertedToInverted', 'InvertedToInverted.html',{'tt':'InvertedToInverted','sb':'InvertedToInverted.html'},],
							['InvertedToRealistic', 'InvertedToRealistic.html',{'tt':'InvertedToRealistic','sb':'InvertedToRealistic.html'},],
							['InteractableToRealistic', 'InteractableToRealistic.html',{'tt':'InteractableToRealistic','sb':'InteractableToRealistic.html'},],
							['InteractableToInverted', 'InteractableToInverted.html',{'tt':'InteractableToInverted','sb':'InteractableToInverted.html'},],
							['RealisticToInteractable', 'RealisticToInteractable.html',{'tt':'RealisticToInteractable','sb':'RealisticToInteractable.html'},],
							['InvertedToRealistic', 'InvertedToRealistic(2).html',{'tt':'InvertedToRealistic','sb':'InvertedToRealistic(2).html'},],
],
],
					['RealisticWithInversion', 'RealisticWithInversion.html',{'tt':'RealisticWithInversion','sb':'RealisticWithInversion.html'},],
					['Inverted', 'Inverted(2).html',{'tt':'Inverted','sb':'Inverted(2).html'},],
],
],
			['ReplaceContent()', 'ReplaceContent()(2).html',{'tt':'ReplaceContent()','sb':'ReplaceContent()(2).html'},
				['SphereInteractionTypes', 'SphereInteractionTypes(2).html',{'tt':'SphereInteractionTypes','sb':'SphereInteractionTypes(2).html'},
					['NonInteractive', 'NonInteractive(3).html',{'tt':'NonInteractive','sb':'NonInteractive(3).html'},
						['Replace content ', 'Replacecontent.html',{'tt':'Replace content ','sb':'Replacecontent.html'},
							['TransitionDissolve', 'TransitionDissolve.html',{'tt':'TransitionDissolve','sb':'TransitionDissolve.html'},],
],
],
					['Interactable', 'Interactable(3).html',{'tt':'Interactable','sb':'Interactable(3).html'},
						['ReplaceInteractionContent()', 'ReplaceInteractionContent()(3).html',{'tt':'ReplaceInteractionContent()','sb':'ReplaceInteractionContent()(3).html'},
							['Replace material 0 on the Inte... ', 'Replacematerial0ontheInteractionSphereto(3).html',{'tt':'Replace material 0 on the InteractionSphere to Content','sb':'Replacematerial0ontheInteractionSphereto(3).html'},],
							['Replace material 1 on the Inte... ', 'Replacematerial1ontheInteractionSphereto(4).html',{'tt':'Replace material 1 on the InteractionSphere to index 0 of it\'s invertedContent list','sb':'Replacematerial1ontheInteractionSphereto(4).html'},],
],
],
],
],
			['ReplaceInteractionContent()', 'ReplaceInteractionContent()(4).html',{'tt':'ReplaceInteractionContent()','sb':'ReplaceInteractionContent()(4).html'},
				['Replace material 0 on the Inte... ', 'Replacematerial0ontheInteractionSphereto(4).html',{'tt':'Replace material 0 on the InteractionSphere to Content','sb':'Replacematerial0ontheInteractionSphereto(4).html'},],
				['Replace material 1 on the Inte... ', 'Replacematerial1ontheInteractionSphereto(5).html',{'tt':'Replace material 1 on the InteractionSphere to index 0 of it\'s invertedContent list','sb':'Replacematerial1ontheInteractionSphereto(5).html'},],
],
			['ToggleInteractable()', 'ToggleInteractable().html',{'tt':'ToggleInteractable()','sb':'ToggleInteractable().html'},],
			['SingleSphereTransition()', 'SingleSphereTransition()(2).html',{'tt':'SingleSphereTransition()','sb':'SingleSphereTransition()(2).html'},
				['If activeContent\'s material is... ', 'IfactiveContent\'smaterialisinindex0ofren.html',{'tt':'If activeContent\'s material is in index 0 of renderer','sb':'IfactiveContent\'smaterialisinindex0ofren.html'},
					['Dissolve', 'Dissolve.html',{'tt':'Dissolve','sb':'Dissolve.html'},
						['Else', 'Else.html',{'tt':'Else','sb':'Else.html'},
							['Materialize', 'Materialize.html',{'tt':'Materialize','sb':'Materialize.html'},],
],
],
],
],
			['SphereToSphereTransition()', 'SphereToSphereTransition()(2).html',{'tt':'SphereToSphereTransition()','sb':'SphereToSphereTransition()(2).html'},
				['If activeContent\'s material is... ', 'IfactiveContent\'smaterialisinindex0ofren(2).html',{'tt':'If activeContent\'s material is in index 0 of renderer','sb':'IfactiveContent\'smaterialisinindex0ofren(2).html'},
					['Dissolve', 'Dissolve(2).html',{'tt':'Dissolve','sb':'Dissolve(2).html'},
						['Else', 'Else(2).html',{'tt':'Else','sb':'Else(2).html'},
							['Materialize', 'Materialize(2).html',{'tt':'Materialize','sb':'Materialize(2).html'},
								['After materialization complete... ', 'Aftermaterializationcompletes.html',{'tt':'After materialization completes','sb':'Aftermaterializationcompletes.html'},],
],
],
],
],
				['Interactionphere.gameobject.Se... ', 'Interactionphere.gameobject.SetActive(Tr.html',{'tt':'Interactionphere.gameobject.SetActive(True)','sb':'Interactionphere.gameobject.SetActive(Tr.html'},],
],
			['ToggleInteraction()', 'ToggleInteraction().html',{'tt':'ToggleInteraction()','sb':'ToggleInteraction().html'},
				['InteractionSphere.gameobject.S... ', 'InteractionSphere.gameobject.SetActive(T.html',{'tt':'InteractionSphere.gameobject.SetActive(True)','sb':'InteractionSphere.gameobject.SetActive(T.html'},],
				['InteractionSphere.SetContent', 'InteractionSphere.SetContent.html',{'tt':'InteractionSphere.SetContent','sb':'InteractionSphere.SetContent.html'},],
],
			['MaterialSetter()', 'MaterialSetter().html',{'tt':'MaterialSetter()','sb':'MaterialSetter().html'},
				['SphereInteractionTypes', 'SphereInteractionTypes(3).html',{'tt':'SphereInteractionTypes','sb':'SphereInteractionTypes(3).html'},
					['NonInteractive', 'NonInteractive(4).html',{'tt':'NonInteractive','sb':'NonInteractive(4).html'},
						['ContentTypes', 'ContentTypes(2).html',{'tt':'ContentTypes','sb':'ContentTypes(2).html'},
							['Realistic', 'Realistic(2).html',{'tt':'Realistic','sb':'Realistic(2).html'},],
							['RealisticWithInversion', 'RealisticWithInversion(2).html',{'tt':'RealisticWithInversion','sb':'RealisticWithInversion(2).html'},],
							['Inverted', 'Inverted(3).html',{'tt':'Inverted','sb':'Inverted(3).html'},],
],
],
					['Interactable', 'Interactable(4).html',{'tt':'Interactable','sb':'Interactable(4).html'},
						['ContentTypes', 'ContentTypes(3).html',{'tt':'ContentTypes','sb':'ContentTypes(3).html'},
							['Realistic', 'Realistic(3).html',{'tt':'Realistic','sb':'Realistic(3).html'},],
							['RealisticWithInversion', 'RealisticWithInversion(3).html',{'tt':'RealisticWithInversion','sb':'RealisticWithInversion(3).html'},],
							['Inverted', 'Inverted(4).html',{'tt':'Inverted','sb':'Inverted(4).html'},],
],
],
],
],
			['GetInactiveMat()', 'GetInactiveMat().html',{'tt':'GetInactiveMat()','sb':'GetInactiveMat().html'},],
			['TransitionTypeDecider()', 'TransitionTypeDecider().html',{'tt':'TransitionTypeDecider()','sb':'TransitionTypeDecider().html'},
				['Content', 'Content.html',{'tt':'Content','sb':'Content.html'},
					['From', 'From.html',{'tt':'From','sb':'From.html'},
						['ContentTypes  | Enum', 'ContentTypes.Enum(3).html',{'tt':'ContentTypes  | Enum','sb':'ContentTypes.Enum(3).html'},
							['Realistic', 'Realistic(4).html',{'tt':'Realistic','sb':'Realistic(4).html'},],
							['Inverted', 'Inverted(5).html',{'tt':'Inverted','sb':'Inverted(5).html'},],
],
],
					['To', 'To.html',{'tt':'To','sb':'To.html'},
						['ContentTypes  | Enum', 'ContentTypes.Enum(4).html',{'tt':'ContentTypes  | Enum','sb':'ContentTypes.Enum(4).html'},
							['Realistic', 'Realistic(5).html',{'tt':'Realistic','sb':'Realistic(5).html'},],
							['Inverted', 'Inverted(6).html',{'tt':'Inverted','sb':'Inverted(6).html'},],
],
],
],
],
],
		['7. GPT Notes', 'GPTNotes.html',{'tt':'7. GPT Notes','sb':'GPTNotes.html'},
			['Use odin for inspector organiz... ', 'Useodinforinspectororganizationlikegroup.html',{'tt':'Use odin for inspector organization like grouping\, dropdowns\, labeling\, tooltiping\, buttons and showifs','sb':'Useodinforinspectororganizationlikegroup.html'},],
],
		['8. SphereMaterial.cs', 'SphereMaterial.cs.html',{'tt':'8. SphereMaterial.cs','sb':'SphereMaterial.cs.html'},
			['SphereMaterial sphereMat', 'SphereMaterialsphereMat.html',{'tt':'SphereMaterial sphereMat','sb':'SphereMaterialsphereMat.html'},],
],

]
];